# Generated by Django 4.1 on 2022-08-28 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=255)),
                ('publisher_email', models.EmailField(max_length=255)),
                ('publisher_site', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('book_price', models.IntegerField()),
                ('book_isbn', models.CharField(max_length=255)),
                ('book_published_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklib.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklib.publisher')),
            ],
            options={
                'unique_together': {('book_name', 'author', 'book_isbn')},
            },
        ),
    ]
